### ISSUE TITLE
No read me

### ISSUE THREAD

**Issue by demitriousj** [richardwestenra/repeater#1]
I was using the hosted version of this tool on your website (http://www.richardwestenra.com/repeater/) which suddenly started 404ing so I have decided to just run the app locally. I was just hoping for few points of information about set up and gotchas.

**Comment by richardwestenra** [comment]
Thanks for posting the issue! I've been having some DNS issues with my website and haven't had time to fix them :/ It seems to sometimes work when you remove the www, but not always?

Anyway, I'll update this soonish. In the meantime, here's some basic info about the project:

I built it using the older Grunt version of [Yeoman Webapp](https://github.com/yeoman/generator-webapp) - here's the [legacy repo branch with the documentation](https://github.com/yeoman/generator-webapp/tree/legacy-grunt).

After cloning the repo, you'll probably need to do the following:
- Install Grunt and Bower globally with `npm install -g grunt-cli bower`
- Install npm and bower modules with `npm install && bower install`
- Run `grunt` for building and `grunt serve` to develop. `--allow-remote` option for remote access.

Hope this helps!

**Comment by richardwestenra** [comment]
@demitriousj Okay my website seems to be back up, so hopefully that should help if you just wanted to use the app
